{% set name = "typed-argument-parser" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/typed-argument-parser-{{ version }}.tar.gz
  sha256: d0e463511549f2951df2968b181b856c2e281be1ab1f4471437de08eb4113ef2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - typing_inspect >=0.7.1
    - docstring_parser >=0.15

test:
  imports:
    - tap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/swansonk14/typed-argument-parser
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Typed argument parser for Python
  description: |
    Tap is a typed modernization of Python's argparse library.
  doc_url: https://github.com/swansonk14/typed-argument-parser
  dev_url: https://github.com/swansonk14/typed-argument-parser

extra:
  recipe-maintainers:
    - jan-janssen
